version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env
    networks:
      - web

  online-payment:
    depends_on:
      - postgres
    container_name: online-payment
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - '5000:5000'
    command: npm run dev 
    networks: 
      - web
    restart: on-failure

  pgadmin:
    container_name: pgadmin
    links:
      - postgres
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env
    networks:
      - web

networks:
  web:
    driver: bridge